# Generated by Django 5.0 on 2023-12-16 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('_2023', '2023'), ('ausconnect', 'Australia'), ('brconnect', 'Brazil'), ('canconnect', 'Canada'), ('chnconnect', 'China'), ('egconnect', 'Egypt'), ('franceconnect', 'France'), ('gerconnect', 'Germany'), ('grcconnect', 'Greece'), ('indconnect', 'India'), ('indonconnect', 'Indonesia'), ('itaconnect', 'Italy'), ('jpsconnect', 'Japan'), ('kconnect', 'Korea'), ('mexconnect', 'Mexico'), ('9jaconnect', 'Nigeria'), ('rusconnect', 'Russia'), ('saconnect', 'South Africa'), ('spnconnect', 'Spanish'), ('thnconnect', 'Thailand'), ('turkconnect', 'Turkey'), ('uaeconnect', 'UAE'), ('ukconnect', 'UK'), ('usaconnect', 'USA')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
